/**
 * Generate plugins/ironsworn/data/assets.yaml from Datasworn (Ironsworn classic).
 *
 * The hand-authored asset list had only each asset's first ability filled in,
 * and some of that text had drifted from the rulebook. This regenerates the
 * full, authoritative set (all three abilities each) from Datasworn.
 *
 *   cd plugins/ironsworn/scribe && bun run scripts/gen-assets-from-datasworn.ts
 *
 * Source: Datasworn @datasworn/ironsworn-classic (CC BY 4.0, Shawn Tomkin).
 * Output shape matches AssetDefinition in
 *   plugins/ironsworn/scribe/src/rules/ironsworn/assets.ts
 */
import { stringify } from "yaml";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const DATASWORN_VERSION = "0.0.10";
const SOURCE_URL = `https://cdn.jsdelivr.net/npm/@datasworn/ironsworn-classic@${DATASWORN_VERSION}/json/classic.json`;

// Collection key → our AssetType; also fixes emit order (matches the old file).
const TYPE_ORDER = ["combat_talent", "companion", "path", "ritual"] as const;
const TYPE_HEADING: Record<string, string> = {
  combat_talent: "Combat Talents",
  companion: "Companions",
  path: "Paths",
  ritual: "Rituals",
};

/** Datasworn markdown → the plain single-line text the rules engine expects. */
function clean(md: string): string {
  let t = md;
  // [label](id:...) / [label](url) → label
  t = t.replace(/\[([^\]]+)\]\([^)]*\)/g, "$1");
  // bold/italic emphasis markers (keep choice bullets, handled below)
  t = t.replace(/\*\*([^*]+)\*\*/g, "$1").replace(/__([^_]+)__/g, "$1");
  // smart punctuation → ASCII
  t = t.replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/…/g, "...");
  // markdown bullet list items → the inline " * " choice style used in this file
  t = t.replace(/\n+\s*[-*]\s+/g, " * ");
  // any remaining newlines → spaces, then collapse runs
  t = t.replace(/\s*\n+\s*/g, " ").replace(/[ \t]{2,}/g, " ").trim();
  return t;
}

function cleanRequirement(md: string): string {
  return clean(md).replace(/\s*\.\.\.$/, ""); // drop the stylistic trailing ellipsis
}

interface OutAbility { name?: string; text: string; default: boolean }
interface OutAsset { name: string; type: string; requires?: string; health?: number; abilities: OutAbility[] }

const ds = (await (await fetch(SOURCE_URL)).json()) as {
  assets: Record<string, { contents: Record<string, {
    name: string;
    requirement?: string | null;
    controls?: Record<string, { field_type?: string; max?: number }>;
    abilities: { enabled?: boolean; name?: string | null; text: string }[];
  }> }>;
};

let yaml = `# Ironsworn Assets
# Source: Datasworn (Ironsworn classic) v${DATASWORN_VERSION} — CC BY 4.0, Shawn Tomkin
#   ${SOURCE_URL}
# GENERATED by plugins/ironsworn/scripts/gen-assets-from-datasworn.ts — do not edit by hand.
# Re-run the generator to update. Only abilities marked "default: true" are
# active at character creation; companions carry a health track.
`;

let total = 0;
for (const type of TYPE_ORDER) {
  const collection = ds.assets[type];
  if (!collection) throw new Error(`missing collection: ${type}`);
  const assets: OutAsset[] = [];
  for (const a of Object.values(collection.contents)) {
    const asset: OutAsset = { name: a.name, type };
    if (a.requirement) asset.requires = cleanRequirement(a.requirement);
    const healthMax = a.controls?.["health"]?.max;
    if (typeof healthMax === "number") asset.health = healthMax;
    asset.abilities = a.abilities.map((ab) => {
      const out: OutAbility = {} as OutAbility;
      if (ab.name) out.name = ab.name;
      out.text = clean(ab.text ?? "");
      out.default = Boolean(ab.enabled);
      return out;
    });
    assets.push(asset);
  }
  total += assets.length;
  yaml += `\n# ─── ${TYPE_HEADING[type]} ${"─".repeat(Math.max(0, 60 - TYPE_HEADING[type]!.length))}\n\n`;
  yaml += stringify(assets, { lineWidth: 0 });
}

// scripts/ → scribe → ironsworn, then /data/assets.yaml
const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "..", "..", "data", "assets.yaml");
writeFileSync(outPath, yaml, "utf-8");
console.log(`Wrote ${total} assets to ${outPath}`);
